"""
AI Health Report Generator v2.0
Generates comprehensive PDF health reports.
"""

import json
from datetime import datetime

try:
    from fpdf import FPDF
    FPDF_OK = True
except ImportError:
    try:
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import A4
        REPORTLAB_OK = True
        FPDF_OK = False
    except ImportError:
        FPDF_OK = False
        REPORTLAB_OK = False

import base64
import io


class HealthReport:
    """Generate a structured health report dict."""

    def generate(self, report_data: dict) -> dict:
        user = report_data.get("user", {})
        predictions = report_data.get("predictions", [])
        health_score = report_data.get("health_score", {})
        diet_plan = report_data.get("diet_plan", {})
        ocr_data = report_data.get("ocr_data", {})

        report = {
            "report_id": f"HR-{datetime.now().strftime('%Y%m%d-%H%M%S')}",
            "generated_at": datetime.now().strftime("%d %B %Y, %I:%M %p"),
            "patient_info": {
                "name": user.get("name", "Patient"),
                "age": user.get("age", "N/A"),
                "gender": user.get("gender", "N/A"),
                "location": user.get("location", "N/A"),
            },
            "health_summary": {
                "health_score": health_score.get("health_score", "N/A"),
                "risk_level": health_score.get("risk_level", "N/A"),
                "bmi": health_score.get("bmi", {}).get("bmi", "N/A"),
                "bmi_category": health_score.get("bmi", {}).get("category", "N/A"),
            },
            "predictions": predictions[:3],
            "top_disease": predictions[0].get("disease", "N/A") if predictions else "N/A",
            "recommended_specialist": predictions[0].get("specialist", "General Physician") if predictions else "General Physician",
            "medicines_from_prescription": ocr_data.get("medicines", []),
            "diet_summary": {
                "calorie_target": diet_plan.get("calorie_target", "N/A"),
                "diet_type": diet_plan.get("diet_type", "N/A"),
            },
            "recommendations": health_score.get("recommendations", []),
            "lifestyle_advice": [
                "Drink 8-10 glasses of water daily",
                "Get 7-8 hours of quality sleep",
                "Exercise at least 30 minutes, 5 days a week",
                "Eat a balanced diet rich in fruits and vegetables",
                "Avoid smoking and limit alcohol consumption",
                "Schedule regular health checkups"
            ],
            "disclaimer": (
                "⚠️ IMPORTANT DISCLAIMER: This health report is generated by an AI system "
                "and is for informational purposes ONLY. It does NOT constitute a medical diagnosis "
                "or prescription. Always consult a qualified healthcare professional for medical advice, "
                "diagnosis, and treatment. In case of emergency, call 108 (Ambulance) immediately."
            ),
            "emergency_contacts": {
                "ambulance": "108",
                "emergency": "112",
                "health_helpline": "104"
            }
        }

        return report

    def to_pdf_base64(self, report: dict) -> str:
        """Generate PDF and return as base64 string."""
        if FPDF_OK:
            return self._generate_fpdf(report)
        return self._generate_text_report_base64(report)

    def _generate_fpdf(self, report: dict) -> str:
        """Generate PDF using fpdf2."""
        pdf = FPDF()
        pdf.add_page()
        pdf.set_margins(15, 15, 15)

        # Header
        pdf.set_fill_color(37, 99, 235)
        pdf.rect(0, 0, 210, 40, 'F')
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_xy(15, 10)
        pdf.cell(180, 10, "HealthPredict AI — Health Report", align="C", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.set_xy(15, 25)
        pdf.cell(180, 8, f"Generated: {report.get('generated_at', '')}", align="C", ln=True)

        pdf.ln(15)
        pdf.set_text_color(0, 0, 0)

        # Patient Info
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "Patient Information", ln=True)
        pdf.set_draw_color(37, 99, 235)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "", 11)
        pi = report.get("patient_info", {})
        pdf.cell(0, 7, f"Name: {pi.get('name', 'N/A')}   |   Age: {pi.get('age', 'N/A')}   |   Gender: {pi.get('gender', 'N/A')}", ln=True)
        pdf.ln(5)

        # Health Summary
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "Health Summary", ln=True)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "", 11)
        hs = report.get("health_summary", {})
        pdf.cell(0, 7, f"Health Score: {hs.get('health_score', 'N/A')}/100   |   Risk Level: {hs.get('risk_level', 'N/A')}", ln=True)
        pdf.cell(0, 7, f"BMI: {hs.get('bmi', 'N/A')} kg/m²   |   BMI Category: {hs.get('bmi_category', 'N/A')}", ln=True)
        pdf.ln(5)

        # Predictions
        predictions = report.get("predictions", [])
        if predictions:
            pdf.set_font("Helvetica", "B", 14)
            pdf.cell(0, 8, "AI Disease Risk Assessment", ln=True)
            pdf.line(15, pdf.get_y(), 195, pdf.get_y())
            pdf.ln(3)
            pdf.set_font("Helvetica", "", 11)
            for i, pred in enumerate(predictions[:3], 1):
                conf = pred.get("confidence_pct", pred.get("prob", 0) * 100)
                pdf.cell(0, 7, f"{i}. {pred.get('disease', 'N/A')} — Confidence: {conf:.0f}%", ln=True)
            pdf.set_font("Helvetica", "I", 10)
            pdf.cell(0, 7, "* This is NOT a diagnosis. Consult a doctor.", ln=True)
            pdf.set_font("Helvetica", "", 11)
            pdf.cell(0, 7, f"Recommended Specialist: {report.get('recommended_specialist', 'General Physician')}", ln=True)
            pdf.ln(5)

        # Recommendations
        recs = report.get("recommendations", [])
        if recs:
            pdf.set_font("Helvetica", "B", 14)
            pdf.cell(0, 8, "Health Recommendations", ln=True)
            pdf.line(15, pdf.get_y(), 195, pdf.get_y())
            pdf.ln(3)
            pdf.set_font("Helvetica", "", 11)
            for rec in recs:
                clean_rec = rec.encode('latin-1', errors='replace').decode('latin-1')
                pdf.cell(0, 7, f"- {clean_rec}", ln=True)
            pdf.ln(5)

        # Disclaimer
        pdf.set_fill_color(254, 249, 195)
        pdf.set_font("Helvetica", "I", 9)
        disc = report.get("disclaimer", "")
        clean_disc = disc.encode('latin-1', errors='replace').decode('latin-1')
        pdf.multi_cell(0, 6, clean_disc, fill=True)

        # Emergency contacts
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 7, "Emergency: Call 108 (Ambulance) | 112 (Emergency) | 104 (Health Helpline)", ln=True)

        # Output
        pdf_output = pdf.output(dest='S')
        if isinstance(pdf_output, str):
            pdf_bytes = pdf_output.encode('latin-1')
        else:
            pdf_bytes = bytes(pdf_output)
        return base64.b64encode(pdf_bytes).decode('utf-8')

    def _generate_text_report_base64(self, report: dict) -> str:
        """Fallback: generate a text report as base64 when PDF libraries unavailable."""
        lines = [
            "=" * 60,
            "HEALTHPREDICT AI — HEALTH REPORT",
            f"Generated: {report.get('generated_at', '')}",
            f"Report ID: {report.get('report_id', '')}",
            "=" * 60,
            "",
            "PATIENT INFORMATION",
            "-" * 40,
        ]
        pi = report.get("patient_info", {})
        lines += [f"Name: {pi.get('name')}", f"Age: {pi.get('age')}", f"Gender: {pi.get('gender')}", ""]
        hs = report.get("health_summary", {})
        lines += ["HEALTH SUMMARY", "-" * 40,
                  f"Health Score: {hs.get('health_score')}/100",
                  f"Risk Level: {hs.get('risk_level')}",
                  f"BMI: {hs.get('bmi')} ({hs.get('bmi_category')})", ""]

        lines += ["AI DISEASE RISK ASSESSMENT", "-" * 40]
        for i, p in enumerate(report.get("predictions", [])[:3], 1):
            conf = p.get("confidence_pct", p.get("prob", 0) * 100)
            lines.append(f"{i}. {p.get('disease')} — {conf:.0f}% confidence")
        lines += ["", "DISCLAIMER", "-" * 40, report.get("disclaimer", ""), "",
                  "Emergency: 108 (Ambulance) | 112 (Emergency) | 104 (Health Helpline)"]

        text = "\n".join(lines)
        return base64.b64encode(text.encode('utf-8')).decode('utf-8')


_report_generator = HealthReport()


def generate_health_report(report_data: dict) -> dict:
    """Generate health report from user data."""
    report = _report_generator.generate(report_data)
    try:
        pdf_b64 = _report_generator.to_pdf_base64(report)
        report["pdf_base64"] = pdf_b64
        report["pdf_available"] = True
    except Exception as e:
        report["pdf_available"] = False
        report["pdf_error"] = str(e)
    return report
